### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by M5218** [lancopku/superAE#4]
Traceback (most recent call last):
  File "train.py", line 343, in <module>
    main()
  File "train.py", line 337, in main
    logging("Best %s score: %.2f\n" % (metric, max(scores[metric])))
ValueError: max() arg is an empty sequence

当我用partⅡ做训练集，partⅢ做测试集时，出现该错误信息怎么解决呢？

**Comment by n1ghtmar4** [comment]
您好，请问这个数据集可以分享给我吗

**Comment by M5218** [comment]
> 您好，请问这个数据集可以分享给我吗

给个邮箱呗

**Comment by n1ghtmar4** [comment]
> Traceback (most recent call last):
> File "train.py", line 343, in 
> main()
> File "train.py", line 337, in main
> logging("Best %s score: %.2f\n" % (metric, max(scores[metric])))
> ValueError: max() arg is an empty sequence
> 
> 当我用partⅡ做训练集，partⅢ做测试集时，出现该错误信息怎么解决呢？

你好，收到您的回复了，我的邮箱是xjwray@qq.com ,谢谢您的分享。

**Comment by n1ghtmar4** [comment]
> Traceback (most recent call last):
> File "train.py", line 343, in 
> main()
> File "train.py", line 337, in main
> logging("Best %s score: %.2f\n" % (metric, max(scores[metric])))
> ValueError: max() arg is an empty sequence
> 
> 当我用partⅡ做训练集，partⅢ做测试集时，出现该错误信息怎么解决呢？

你好，收到您的回复了，我的邮箱是xjwray@qq.com ,谢谢您的分享。

**Comment by n1ghtmar4** [comment]
> > 您好，请问这个数据集可以分享给我吗
> 
> 给个邮箱呗
我的邮箱是xjwray@qq.com ,谢谢您的分享。

**Comment by n1ghtmar4** [comment]
> 您好，请问这个数据集可以分享给我吗



> 您好，请问这个数据集可以分享给我吗

**Comment by 3401mm** [comment]
留个邮箱吧

**Comment by n1ghtmar4** [comment]
> 您好，请问这个数据集可以分享给我吗

1

**Comment by angeluau** [comment]
您好，可以把调通的代码和数据集打包发给我，我们可以一起讨论一下，我的邮箱2215346277@qq.com，万分感谢

**Comment by hongBry** [comment]
@3401mm  您好，请问这个数据集也可以分享给我吗，邮箱1182936254@qq.com，十分感谢

**Comment by angeluau** [comment]
> Traceback (most recent call last):
> File "train.py", line 343, in 
> main()
> File "train.py", line 337, in main
> logging("Best %s score: %.2f\n" % (metric, max(scores[metric])))
> ValueError: max() arg is an empty sequence
> 
> 当我用partⅡ做训练集，partⅢ做测试集时，出现该错误信息怎么解决呢？

请问你的模型有调通吗？
