### ISSUE TITLE
2215346277@qq.com> 您好，请问这个数据集可以分享给我吗

### ISSUE THREAD

**Issue by angeluau** [lancopku/superAE#7]
给个邮箱呗

_Originally posted by @3401mm in https://github.com/lancopku/superAE/issues/4#issuecomment-431721457_

**Comment by shumingma** [comment]
因为涉及到数据集的版权问题，请向数据集的原作者申请：http://icrc.hitsz.edu.cn/Article/show/139.html

**Comment by angeluau** [comment]
> 因为涉及到数据集的版权问题，请向数据集的原作者申请：http://icrc.hitsz.edu.cn/Article/show/139.html

**Comment by angeluau** [comment]
> 因为涉及到数据集的版权问题，请向数据集的原作者申请：http://icrc.hitsz.edu.cn/Article/show/139.html

请问你在调模型的过程中没有发现有缺失文件吗？朋友可以加一个qq吗？和你交流一下，2215346277
